name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  #run at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #checkout the code from the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      ##install necessary dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest flake8

      #run pytest to execute tests
      - name: Run pytest
        run: pytest

      #run flake8 for code quality checks
      - name: Run flake8
        run: flake8 .
